"""initial_paper_platform

Revision ID: dd7ccd916399
Revises:
"""

from alembic import op
import sqlalchemy as sa

revision = "dd7ccd916399"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cash", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("starting_cash", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("kill_switch", sa.Boolean(), nullable=False),
        sa.Column("data_source", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("context_id", sa.String(length=80), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=80), nullable=False),
        sa.Column("actor", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_event"), "audit_events", ["event"], unique=False)
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("dataset", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "historical_candles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("instrument_id", sa.String(length=80), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instrument_id", "timestamp", "interval"),
    )
    op.create_index(
        op.f("ix_historical_candles_instrument_id"),
        "historical_candles",
        ["instrument_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_candles_timestamp"), "historical_candles", ["timestamp"], unique=False
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("underlying", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_snapshots_timestamp"), "market_snapshots", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_market_snapshots_underlying"), "market_snapshots", ["underlying"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=80), nullable=False),
        sa.Column("intent", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["market_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("instrument_id", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("entry_fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("mark_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proposal_id"),
    )
    op.create_table(
        "risk_evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=80), nullable=False),
        sa.Column("decision", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["market_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_evaluations_proposal_id"), "risk_evaluations", ["proposal_id"], unique=False
    )
    op.create_table(
        "paper_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=36), nullable=True),
        sa.Column("position_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("instrument_id", sa.String(length=80), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("fill_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fee", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "idempotency_key"),
        sa.UniqueConstraint("proposal_id"),
    )
    op.create_index(
        op.f("ix_paper_orders_position_id"), "paper_orders", ["position_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_orders_position_id"), table_name="paper_orders")
    op.drop_table("paper_orders")
    op.drop_index(op.f("ix_risk_evaluations_proposal_id"), table_name="risk_evaluations")
    op.drop_table("risk_evaluations")
    op.drop_table("positions")
    op.drop_table("proposals")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_market_snapshots_underlying"), table_name="market_snapshots")
    op.drop_index(op.f("ix_market_snapshots_timestamp"), table_name="market_snapshots")
    op.drop_table("market_snapshots")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_historical_candles_timestamp"), table_name="historical_candles")
    op.drop_index(op.f("ix_historical_candles_instrument_id"), table_name="historical_candles")
    op.drop_table("historical_candles")
    op.drop_table("backtest_runs")
    op.drop_index(op.f("ix_audit_events_event"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("agent_runs")
    op.drop_table("accounts")
    # ### end Alembic commands ###
